### ISSUE TITLE
Memos index view is only displaying the memo for the location with the highest location_id.

### ISSUE THREAD

**Issue by Mei152** [Mei152/hours_import#103]

**Comment by Mei152** [comment]
Found the issue:

`  PayrollRun.new(params[:check_date]).uploaded_files.each { |file| @memos = [] << {location: file.location.number, memo: file.memo} if file.memo.size > 0 }`

@memos is being set to an empty array upon every iteration.

The fix will be submitted as a part of #97

**Comment by mkwiatkowski** [comment]
Good catch!
