### ISSUE TITLE
Uploaded hours should be stored in the database

### ISSUE THREAD

**Issue by Mei152** [Mei152/hours_import#11]
To be discussed

**Comment by mkwiatkowski** [comment]
I think this is a non-issue, should probably become part of #10. While I can imagine creating a form separately from code that saves it to the DB I don't think it's feasible in this case. Feel free to argue otherwise if you feel strongly about it.

**Comment by Mei152** [comment]
I am not sure. There will be some data modification required before it would be suitable for storage in the DB. Here is a small sample of the file format we will be importing: 
[current_source_file_sample.txt](https://github.com/Mei152/hours_import/files/54149/current_source_file_sample.txt)

We will be storing only the first four fields from the source file, but will need to add additional fields to it. This brings up a discussion I would like to have. Do we want to store the data in a relational form, or tabular? My gut tells me that a tabular format would be better. I have opened a new task for us to work this out. #15

Just so it is on our radar, the store locations will be migrating to a new POS system (our source) in June 2016, so will will eventually have to make provisions for importing differently formatted files than what we will be using now.
[future_source_file_one site.txt](https://github.com/Mei152/hours_import/files/54245/future_source_file_one.site.txt)
[future_source_file_three sites.txt](https://github.com/Mei152/hours_import/files/54246/future_source_file_three.sites.txt)
These files will require additional processing. That they have the actual date parameters is a big win as there will be no question that the beginning and ending dates of the data being uploaded is in fact consistent with the beginning and ending dates of the time period the data is being associated with upon being uploaded. As it stands now, we have no way of knowing that data being uploaded for a one week time period doesn't contain hours for more, or less, than 7 days. Or if it is actually for the correct week. This is scary.
