### ISSUE TITLE
refactor validate_file method - move part of it into time_records_validation_batch

### ISSUE THREAD

**Issue by Mei152** [Mei152/hours_import#25]

**Comment by mkwiatkowski** [comment]
Nice. I can see that you fixed this in 78b15b6cd1bb895824f5eae140208551f0cae0e2.

Two things that will make my (and yours in the future) work easier:

- When you close a ticket merge your work into master. If the code is stable enough to close a ticket, it's stable enough to merge into master.
- Include the ticket number in your commit messages. This way github will connect commit and the ticket together. For example in 78b15b6cd1bb895824f5eae140208551f0cae0e2 you could've used a message like this: `Refactoring: move part of UploadedFile#validate_file into TimeRecordsValidationBatch#run_validations. #25`. You can even close ticket with the right commit message, see the docs here: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by Mei152** [comment]
>When you close a ticket merge your work into master. If the code is stable enough to close a ticket, it's stable enough to merge into master

The code I refactored may primarily originate from an active branch for which a pull request was never issued. Therefore the code was never subject to your review, which is why I would not take it upon myself to merge into master. I am concerned that too much new code was written without a pull request; that I failed to define a clean cutoff point to start a new branch. Can you please advise on pull request frequency?

**Comment by mkwiatkowski** [comment]
The usual process looks like this:

1. Implement ticket in a branch.
2. Create a pull request.
3. Back-and-forth between author and reviewer. Code in the branch may be updated multiple times.
4. Pull request is approved and merged into master.
5. Ticket is closed.

This works well when tickets are all independent of each other and waiting a few days for a review is not a problem. Then the developer can create a PR and while waiting for comments start work on something else.

I don't think that process will work well for this project in its current state. It's still in its infancy and there's still a lot of dependencies between tickets. So I say do it this way:

1. Implement the ticket in master, marking each commit with a ticket number.
2. Close the ticket when it's been implemented.
3. I'll review commits directly from master.

**Comment by Mei152** [comment]
Okay, I completed tickets #21 and #22. The work had already been initiated on the process-file branch, so I wasn’t able to originate the fixes from master. I did include the issue numbers in the commit messages.

 

I would like to do a pull request for the process-file branch so we can merge it into master and I can start following your prescribed workflow.

 

Please advise if this is a good idea.

**Comment by mkwiatkowski** [comment]
You can merge without making a pull request. Just do this from the console:

```
git checkout master
git merge process-file
git push
```

That's it - merging your branch into master and pushing those changes up to github.

**Comment by Mei152** [comment]
We need to have the discussion about the time_periods table. The process-file branch has some work on it pertaining to this concept, and I don’t want to merge it into master if we going in a different direction.

**Comment by mkwiatkowski** [comment]
This branch also has a lot of work not related to time periods, so you can't throw it away completely either. I'd suggest merging and then manually removing/refactoring if the concept turns out differently.

**Comment by mkwiatkowski** [comment]
Oh, and I'll post an answer in that other discussion today.
