### ISSUE TITLE
add more file validation states

### ISSUE THREAD

**Issue by Mei152** [Mei152/hours_import#26]

**Comment by Mei152** [comment]
states include 'pending', 'processing', 'failed', 'valid', 'valid_with_warnings', 'accepted', 'accepted_with_warnings'

**Comment by mkwiatkowski** [comment]
What's the difference between "valid" and "accepted"? I think we agreed
files with no warnings don't require acceptance from the user.

**Comment by Mei152** [comment]
Yes, “Accepted” was not a part of our conversation.

 

I was thinking that maybe the two file types “valid”, and “valid_with_warnings”, should take similar paths in life. 

 

Valid with_warnings can be approved by clicking a button. Maybe the same should hold true for valid. When valid_with _warnings is approved by a button being clicked, its status changes to accepted_with _warnings. To be consistent, valid should be changed to accepted by clicking a button.

 

This would allow a button to appear if the file is in either of the two “acceptable” states. If the button is clicked, both files can be affected by the same controller action, and eventually lead to the same view being rendered. The whole scenario seems cleaner to me in that there is more consistency in the way things work, and more consistency in the user experience.

 

Your thoughts?

**Comment by mkwiatkowski** [comment]
OK, that can work.

Here's how the state machine looks like now:

```
                 +----------> failed
                 |
pending --> processing -----> valid ------------> accepted
                 |
                 +------> valid_with_warnings --> accepted_with_warnings
```

One starting state ("pending") and three end states ("failed", "accepted" and "accepted_with_warnings").

It may be easier to code for this alternative, where you have only two end states:

```
                 +----------> failed
                 |
pending --> processing -----> valid -----------> accepted
                 |                                 ^
                 +------> valid_with_warnings -----+
```

I'm just not sure if the information that there *were* warnings, but without knowing what those warnings were is useful.

**Comment by Mei152** [comment]
I agree that the value of having  both accepted and accepted_with_warnings sates is questionable. I was asking myself that too. Having only accepted is probably the better way to go.

**Comment by Mei152** [comment]
By the way, thanks for the quick critique on my modifying states.

 

I am assuming you were alerted to my change because I created a ticket, and completed it.

Is this a pattern I should follow when making substinative changes?

**Comment by mkwiatkowski** [comment]
Yeah, I get ticket notifications directly to my inbox.

As noted at the end of our last meeting: make sure you have a ticket for everything you do. Close the ticket right after implementing it.

**Comment by Mei152** [comment]
states now include 'pending', 'processing', 'failed', 'valid', 'valid_with_warnings', and 'accepted', as per our e-mail conversation.
