### ISSUE TITLE
Add functionality to persist accepted time records

### ISSUE THREAD

**Issue by Mei152** [Mei152/hours_import#29]
This should be triggered by file acceptance.

**Comment by Mei152** [comment]
I thought before that persistence of the time records should be triggered by the uploaded file achieving "accepted" validation status. I now think persistence should be its own insulated process under the control of an admin, and state be indicated by its own dedicated attribute.

**Comment by Mei152** [comment]
I wanted to have persisting time records wrapped in a transaction, but I am not sure this is going to work being that these are kind of nested blocks. I will keep doing research on it. Just wanted to let you know what I am puzzling over.

    ActiveRecord::Base.transaction do
      CSV.parse(self.file, options) do |row|
        row = row.to_hash
        row.keep_if { |key, value| !(fields_to_drop.include? key) }
        row[:location_id] = location_id
        row[:location_number] = Location.find(location_id).number
        row[:uploaded_file_id] = id
        record = TimeRecord.new(row)
        record.save!
      end
    end

**Comment by Mei152** [comment]
What is your opinion on which callback is best to use in setting default values for attributes?
I've used before_validation, but I just saw an example that used after_initialize that was compelling.

**Comment by Mei152** [comment]
Functionality is now present. There are details that I would like to clean up, but we can create new tickets for them.

**Comment by Mei152** [comment]
I thought about my question earlier about before_validation and after_initialize, and I can imagine that after_initialize would be handy if you wanted the defaults to appear in the 'new' view, whereas before_validation would present the user with a totally blank view unless defaults were specified in the view code. This brings me to a new question: under what circumstances would you want to implement default values in the view coded rather than using after_initialize?

**Comment by mkwiatkowski** [comment]
> I wanted to have persisting time records wrapped in a transaction, but I am not sure this is going to work being that these are kind of nested blocks. I will keep doing research on it. Just wanted to let you know what I am puzzling over.

This will work, the transaction will commit once the whole CSV file has been parsed. So either all time records will be saved or none.

**Comment by mkwiatkowski** [comment]
> I thought about my question earlier about before_validation and after_initialize, and I can imagine that after_initialize would be handy if you wanted the defaults to appear in the 'new' view, whereas before_validation would present the user with a totally blank view unless defaults were specified in the view code. This brings me to a new question: under what circumstances would you want to implement default values in the view coded rather than using after_initialize?

Since it is possible to have multiple forms in different parts of the application backed up by the same model sometimes you may want to have defaults specific to a view/form. This is a pretty narrow use case though, so I'd recommend using `after_initialize` in most cases.

**Comment by Mei152** [comment]
fixed 03d2d04
