### ISSUE TITLE
Admin should be able to create user accounts

### ISSUE THREAD

**Issue by Mei152** [Mei152/hours_import#3]
Fields that need to be filled in to create a user:

- email (string)
- name (string)
- location (chosen from the list of defined locations, see #5)
- password (string)
- role (string) this will require installing the Pundit gem, see #9

This functionality should be available through the admin panel (see #6).

![admin user maintenance](https://cloud.githubusercontent.com/assets/11021008/11611794/ec4467c8-9bad-11e5-990a-9cb9ac33b5ef.png)

**Comment by Mei152** [comment]
Currently, I have a select list for user role. I would like to have the location field become disabled if role "admin" is selected. This would best be accomplished with JavaScript I suspect. Maybe I should wait until the front end course to worry about it?

**Comment by mkwiatkowski** [comment]
Yes, JavaScript solution would be required here. Close this ticket for now and make a new one just for this: "the location field should become disabled if role "admin" is selected".
