### ISSUE TITLE
Dynamically generate time periods seed date

### ISSUE THREAD

**Issue by Mei152** [Mei152/hours_import#33]
Need to figure out how app should decide which base date it should use in generating lists of time periods. The functionality may be different depending on the context: one method for new file uploads, another if user wants to upload a file for a time period that has already had a file uploaded against it, i.e. overwrite, yet another for retrieval of historical uploads.

**Comment by Mei152** [comment]
I am thinking a possible approach for deciding what time period a user's uploaded file would be associated with is:  have a "configuration setting" in the admin panel that would set the base date for which time periods would be generated against. The default time period for each location would automatically increment by one week upon a successful file upload associated with that time period and location.This might be best accomplished by looking back in the uploaded_files table, and grabbing the last period end date for files associate with each location.

**Comment by Mei152** [comment]
Added a method for a part of this functionality 762cf4bf0bb282c29a7b18d6c1fae6c36a1f70d4
but much of this depends on user privileges, so I will work on getting adding of users, authentication, etc. set up first.

**Comment by mkwiatkowski** [comment]
How about making this a default: generate time periods for the last 3 months. That's 13 weeks. Would this work, and if not why?

For retrieval of historical uploads you can simply use the oldest upload's `time_period_start_date` attribute.

**Comment by Mei152** [comment]
I was thinking of limiting the time periods available for the user to upload against to only those periods for which a file was not yet successfully uploaded, plus maybe two into the future.  Experience has taught me that if you limit people's options, you limit possibilities for bad things to happen.

**Comment by Mei152** [comment]
This could be coupled with some functionality that would limit the ability to overwrite previously uploaded file to admins.

**Comment by Mei152** [comment]
And when I say "experience has taught me that if you limit people's options, you limit possibilities for bad things to happen", I include myself in that.

**Comment by Mei152** [comment]
When I think about it further, there is no reason for the user to have any other choice of time period to upload against except the most immediate one.

**Comment by mkwiatkowski** [comment]
> When I think about it further, there is no reason for the user to have any other choice of time period to upload against except the most immediate one.

What if they missed a week?

**Comment by Mei152** [comment]
The way I am thinking of doing it, they wouldn't be able to miss a week because the period wouldn't increment to the next until a file was uploaded for the present period. This all makes sense for the purpose of uploading hours already worked. It may be a different scenario if/when we were allow the app to accept projected hours for budgeting purposes. I'm not sure if we should worry about that hypothetical right now. There could be a whole slew of dedicated code for that functionality besides determining what time periods show up on the page.

**Comment by mkwiatkowski** [comment]
OK, that makes sense. Sometimes the simplest solution works best! :-)
