### ISSUE TITLE
Fix associations between users and locations

### ISSUE THREAD

**Issue by Mei152** [Mei152/hours_import#40]
I need to fix the association I attempted to create in this commit: 842fccf80929d8e406faf55f18edd9121a842acb

New issue #39 created to address this.

**Comment by Mei152** [comment]
Fixed by commit: 8e0e662ef9de2ad916b53d351f959643c1c67a6e

**Comment by Mei152** [comment]
Fixed again by commit: c65c99c7e67325883ab34b5503ce29410c23d561

**Comment by mkwiatkowski** [comment]
Good, this model is indeed simpler.
