### ISSUE TITLE
Add handling of foreign key violation errors

### ISSUE THREAD

**Issue by Mei152** [Mei152/hours_import#42]
Got a foreign key violation error when trying to delete a location that a user was assigned to.
There must be a graceful way to handle what is likely a common scenario by presenting the user with a nice error message through the app interface rather than having the app blow up.

This also raises the question of how to deal with other associated records, such as uploaded files. It is fine to change the location associated with a user, but it would not be appropriate to change the location associated with historical uploaded files. 

Also, what if a location was legitimately closed, and we wanted it not to appear in selection lists. Maybe we should allow locations to be designated as "inactive".

**Comment by mkwiatkowski** [comment]
Deleting records is indeed problematic to associations. The problem is easiest to solve when the association is optional. For example, if a user can (but doesn't have to) belong to a location then you can simply set the `location_id` to `NULL` when the location is removed.

Another option is the one you listed: instead of deleting the location record mark it as "inactive". This leaves the association intact, but care must be taken in multiple places in the application (as well as in all future code) that such location is treated as inactive. Possibly users associated with inactive locations should be treated differently as well. Overall this solution may cause a high maintenance cost in the future, so before going this way I'd make absolutely sure I need it.

When the association is required forbidding deletes is probably the best option. You already have that, so the remaining issue is error handling. Using `dependent: :restrict_with_exception` will probably do what you want and then you'll only need to `rescue` the exception in the controller.

If you want to do additional research Rails has more built-in solutions, just search for mentions of `:dependent` option in the association guide: http://guides.rubyonrails.org/association_basics.html

**Comment by Mei152** [comment]
I have to think on this a bit. Using restrict_with_exception is tempting just because it is something new I can learn, but maybe not requiring users to be associated with a location is not such a bad idea either.

I do have a somewhat related question: Admin should be able to upload files for any location. If you recall, I suggested that we could just include some conditionals that check if the current user is an admin. Maybe this would grant them access to a view that enables uploads for any location, and any time period. This seems easy enough. But, then I wondered about creating a location #0, which would be called All. Then we could test if a user is associated with location All, and that could open up possibilities for them. Can you see pros/cons to each method?

**Comment by Mei152** [comment]
After thinking on this, the location #0 All idea is not a good one. I can imagine it causing havoc with other things down the road. Also, I will make the assignment of a User to a Location optional, although this will require some that upload functionality is gracefully blocked if a user has no associated location, unless, of course, they are an admin.

**Comment by Mei152** [comment]
Should probably cause a message to be displayed informing admin if the location they are deleting will orphan any users.

**Comment by Mei152** [comment]
Please see commit df6c0c3

I do have concerns about the before_destroy callback on Location. This is in place to set each associated user's location_id to nil when a location is deleted.

I was thinking that maybe the location deletion, and the setting of users_id to nil should be included together in a transaction. I did use user.save! in location#set_users_location_id_to_nil to at least cause a ruckus if that doesn't go well, but I have no handling in place.

If a transaction were used, the controller seems like the easiest place to put it, but I would rather keep it out of there if I could.

Not sure what direction to take. Maybe I am worrying too much, because I would imagine that callbacks are used extensively for such things

**Comment by mkwiatkowski** [comment]
Quoting http://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html#module-ActiveRecord::Callbacks-label-Transactions

```
The entire callback chain of a save, save!, or destroy call runs within a transaction.
That includes after_* hooks. If everything goes fine a COMMIT is executed once
the chain has been completed.
```

So it is already taken care of.

Additionally, what you have built here is already part of Rails through the `dependent` option. Put `has_many :users, dependent: :nullify` in the `Location` model. See http://apidock.com/rails/v4.2.1/ActiveRecord/Associations/ClassMethods/has_many for details.

**Comment by Mei152** [comment]
Commit 035d03254b938c88018e230cbe91cc4fe794bc14 fixes this. I haven't closed the issue yet because I haven't figured out why it didn't auto close due to my commit message. Don't want to destroy the evidence.

**Comment by mkwiatkowski** [comment]
> Commit 035d032 fixes this. I haven't closed the issue yet because I haven't figured out why it didn't auto close due to my commit message. Don't want to destroy the evidence.

The tooltip says it all:

![tooltip](https://cloud.githubusercontent.com/assets/51481/13247568/922a0350-da1a-11e5-8a5e-a63c0636b68f.png)

**Comment by Mei152** [comment]
It seems to me that I should not have created issue #50, but, instead should have referenced this issue when making commit 035d03254b938c88018e230cbe91cc4fe794bc14. It definitely made for a convoluted trail.

**Comment by mkwiatkowski** [comment]
I agree, just referencing this issue would be fine. Lesson learned! :-)

**Comment by Mei152** [comment]
So, yes the tooltip explains it (now I know to look for such indicators), but, I don't see where the way this works is all that handy. There is no explicit indicator that the issue is pending closure anywhere that would slap you in the face (at least not that I have found yet) . What would be useful is if, at the main issue index, that the issue was clearly demarcated as pending closure upon merge. I use the index to see what issues need to be worked on, and, from there, it has the appearance that the issue is till open. Am I missing something?

**Comment by mkwiatkowski** [comment]
No, but you could just merge branches into master once you are done with a feature. With issues being so nicely linked to commits I don't need pull requests to review your code effectively.

**Comment by Mei152** [comment]
Maybe this is an idea for a future enhancement contribution I can make towards github when I grow up.
