### ISSUE TITLE
Refactor user views to change on user record persistence status

### ISSUE THREAD

**Issue by Mei152** [Mei152/hours_import#49]

**Comment by Mei152** [comment]
Closed by commit : 3034374

**Comment by Mei152** [comment]
The last commit broke some stuff.

**Comment by Mei152** [comment]
fixed with 2069af4 & 865794f

**Comment by mkwiatkowski** [comment]
There's no need for comments like "fixed with 2069af4 & 865794f" anymore. You already mentioned issue number in the commit messages, so github links the two automatically.
