### ISSUE TITLE
refactor location select box values methods

### ISSUE THREAD

**Issue by Mei152** [Mei152/hours_import#53]

**Comment by mkwiatkowski** [comment]
Not necessarily about this ticket, but as a general comment: it would be best if tickets and commit messages gave some context to the work that was performed. The usual question to ask is "why". For example here I can see you did the refactoring, but why was it performed and why in this specific way?

Just so you know what I mean (no need to update any commits or tickets) here's how I would write the commit message:

> Move `UploadedFile.assignable_locations` method to `Location.admin_file_upload_locations_select_box_values` so that all code related to locations is in a single place.

and here's how I would name the ticket:

> Keep location-related code in the Location model.

**Comment by Mei152** [comment]
Thank you.  This advice is very helpful.

**Comment by Mei152** [comment]
Also, I was under the impression, for whatever reason, that commit messages were intended to be short. I'm not sure I've ever seen one as long as what you just suggested. Just so I understand, you do mean the commit message should be that descriptive, not the ticket description?

**Comment by mkwiatkowski** [comment]
Both, but for different reasons. Tickets are for description of the problem, commits are for description of a solution. Sometimes a complex problem can have a simple solution and vice versa. They both can be arbitrarily long.

You don't have to look for examples further than the official Rails repo: https://github.com/rails/rails/commits/master Just look at some non-merge commits to find both short and long descriptions, depending on a specific commit.
