### ISSUE TITLE
Normal users will need their own file upload view and controller.

### ISSUE THREAD

**Issue by Mei152** [Mei152/hours_import#54]

**Comment by mkwiatkowski** [comment]
Why normal users need a separate view and controller?

**Comment by Mei152** [comment]
I think you have a point here.  The same effect can probably be achieved through conditional instance variable assignments in UploadedFilesController#set_index_view_instance_variables, and view partials. Let me think on it.

I appreciate your questioning me!

**Comment by Mei152** [comment]
Silly idea.

**Comment by mkwiatkowski** [comment]
OK, good. :)
