### ISSUE TITLE
Standardize CSS names to use dashes instead of undescores

### ISSUE THREAD

**Issue by Mei152** [Mei152/hours_import#69]

**Comment by mkwiatkowski** [comment]
I don't think it's essential, so I'd suggest putting it in V2 milestone.

**Comment by Mei152** [comment]
Sorry, I was already into the task. It was something I could do within a small time window.

**Comment by Mei152** [comment]
I did run into something unexpected with replacing time_periods with time-periods as doing a replace all changed some of my variable names and partial calls. Is there a convention for css names to prevent such "collisions"?

**Comment by mkwiatkowski** [comment]
You could prefix all your custom classes with a unique string (e.g. "hi-" for "hours import"), so it's easier to differentiate library classes (e.g. from Bootstrap) from those that are application-specific.

Having said that, you always need to be careful during any refactoring, even as simple one as a rename. Another place where automated tests would help.
