### ISSUE TITLE
Admin should be able to create time periods

### ISSUE THREAD

**Issue by Mei152** [Mei152/hours_import#7]
Attributes for time periods should include:
* start_date (date)
* end_date (date)
* type (string) this should be selected from a drop down list, or radio buttons.

This should be accessible from admin panel #6

**Comment by mkwiatkowski** [comment]
What types will be available?

**Comment by mkwiatkowski** [comment]
Oh sorry, just noticed #8. Can you give an example of a time period type?

**Comment by mkwiatkowski** [comment]
On another note, isn't there a way to just generate those time periods automatically? Some kind of rule/algorithm that would allow for the computer to generate them? Seems quite laborious to manually create time periods.

On the other hand I don't know how many of them you'll have. One for each quarter, each month, each week? Are time periods shared across locations or does each location have its own time periods?

**Comment by Mei152** [comment]
Examples of time period types might be:
- a one week period of actual payroll hours
- a one week period of projected payroll hours for budgeting
- a one month period of actual payroll hours for Affordable Care Act reporting (Obama Care)

Your questioning this leads me to think that time periods should have a description attribute in addition to a name attribute. I added this new requirement to  #8 

Keep in mind that "one week period" does not necessarily mean the same thing in all cases. For one type it might mean Monday through Sunday, for another it might be Sunday through Saturday. A one month period would start on the first day of the month, and end on the last, regardless of what actual weekdays they happen to be.

**Comment by mkwiatkowski** [comment]
Why the data needs to be uploaded by those specific periods? Wouldn't be enough to upload simple monthly data (from 1st to last day of a month) and then do analysis on it with those extra periods? In other words: why time periods are important during uploading, as opposed to later - during analysis?

I don't understand it fully, but I imagine the following scenario:

1. User U uploads data for location L for first week of the year (Jan 4-10 2016)
2. Later on, User U uploads data for location L for the first month of the year (Jan 1-31 2016)

In effect, data for Jan 4-10 is duplicated. Not sure if that's right, so please correct me if I'm wrong. :)

**Comment by Mei152** [comment]
I had a bit to say about this in #11, but I did a little more digging, and a way to handle this in compliance with your way of thinking has presented itself, but I don't think we can take advantage of it until June 2016. This is when the locations will be migrating to a new POS system, and it will have better reporting capabilities.

The new system can produce these reports in CSV format:
[future_source_options.pdf](https://github.com/Mei152/hours_import/files/54948/future_source_options.pdf)

This will provide data at the level of granularity required to build a nice database that would fulfill most of our needs without redundant uploads. I don't believe this same format is available from the current POS system, but I will verify.

This leaves us with two things to discuss:
- how do we get the most short term value out of the data source we have to work with now?
- the new POS system's capabilities still do not provide the data necessary for use in a payroll budgeting app, which is one of the eventual goals. It only tells us what happened. It does not give us anticipated schedules. We need to think on this for a bit, and talk about the budgeting app that will eventually be one of the systems consuming the data this current project is being built to provide.

**Comment by Mei152** [comment]
I am working on the admin panel, and current requirements are that there is a time period maintenance option. I have a rake task written that populates the time_periods table. This is sufficient to get the app working. We can give the admin the ability to add additional time periods, but all the scenarios I have thought up that would allow initial fill of the time periods table through the app interface seem like a bad idea. Can I leave initial fill to a rake task?

**Comment by mkwiatkowski** [comment]
Rake task is OK for initial loads, but what about later on? How those time periods will be created?

Also, I am still not convinced this table is needed. Time and dates are "stable", they are not going to change (e.g. January 12th 2016 is always going to be a Tuesday). Why keep those records in DB instead of generating them on the fly when needed?

**Comment by Mei152** [comment]
Here is what I am trying to accomplish with the time periods table:

 

I would like to have some structure to the submittal of hours worked so there is uniformity in when they are submitted, and what time span they encompass – every Monday, location managers should submit   the hours for the preceding seven days.

 

The manager should receive feedback informing them if their submittal did include hours for each of the seven days in the preceding week, or if it included days outside of the preceding weeks’ start and end date.

 

I’ve had it happen in the past where a store manager submitted aggregated hours for a two week payroll period that included 15 days’ worth of hours. If I had not noticed that that one store’s submittal report’s date range started one day earlier than the other 17 store’s reports’ did, we would have been out some money.

 

The table will contain rows that consist of a start_date (Monday) and an end_date (Sunday).

 

I will ponder your “on the fly” comment.

**Comment by Mei152** [comment]
Just curious if you are finding merit in my idea about the time periods table after my explaining my motivation. It will give the store managers clear cut specifications for their hours submittal, and give us parameters by which to validate their completeness. It will also give us a way to monitor when a time period has had all the stores make a submittal against it, and it is ready for payroll processing. My plan is to create a link table between the time periods table and the file uploaded file table.  let me know if this makes sense to you so,I can continue to make progress. Otherwise, I am certainly open to suggestions.

**Comment by mkwiatkowski** [comment]
I will answer this, but most likely not today, sorry!

**Comment by Mei152** [comment]
No problem. There is a world of stuff out there for me to study up on in the meanwhile.

**Comment by mkwiatkowski** [comment]
OK then. I understand the whole idea and it makes sense. My only nitpick is with the implementation. I'm not sure if you need to store dates in a database. Dates and time periods are fixed - they never change - so why store them at all? Instead of a table that you need to keep filled you could have a method that generates as many periods as you need for a given purpose. It's a more flexible and safe approach.

> My plan is to create a link table between the time periods table and the file uploaded file table. let me know if this makes sense to you so,I can continue to make progress.

Sure, if that makes sense to you, go ahead and do that. It will definitely be easier to talk about concrete implementation.

Alternative to that would be to store start and end date for a period in the uploaded file table, and use a method to generate period details from that. But if my "on-the-fly" idea isn't clear then just do what you feel is right and we can go from there.

**Comment by Mei152** [comment]
closed by commit e9412e5

related point about the base date for time period generation  moved to new issue #33
