### ISSUE TITLE
Admin should be able to view all memos associated with 2 week payroll period.

### ISSUE THREAD

**Issue by Mei152** [Mei152/hours_import#80]

**Comment by mkwiatkowski** [comment]
I don't like how this has been split into commits. "One commit = one file"is **not** the rule to follow!

**Comment by Mei152** [comment]
I understand. I been feeling bad about some of the big commits I've been making recently, so I tried to break this one up. I admit it didn't seem right while I was doing it though.

**Comment by mkwiatkowski** [comment]
Split by logical chunks of functionality only, and not by file or day you've made the changes.
