### ISSUE TITLE
Prevent payroll CSV file from being generated if there are any un-mapped employees.

### ISSUE THREAD

**Issue by Mei152** [Mei152/hours_import#99]

**Comment by mkwiatkowski** [comment]
Interesting corner case!

**Comment by Mei152** [comment]
Should probably issue a warning if any of the uploaded files have not yet been persisted.
Outright preventing a download would be too restrictive because maybe a store location had difficulties uploading their file. The hours for that store could still be manually entered in paycom in an emergency so payroll gets processed on time.

**Comment by Mei152** [comment]
Un-mapped employees are only an issue if they exist on the POS side. It is not unusual to set up a new hire on paycom before they work any hours. We are only concerned that all employees for which hours are submitted on the POS side are paid. For their hours to be output in the CSV file, they would have to be mapped.

**Comment by Mei152** [comment]
Now that I think about it more... obviously, if a file is sitting there in un-persisted status, it has already been uploaded by the store location.I will just disable the csv download button if there are any in un-persisted status. Now, if there are missing files, that is another story. For now, I am going to rely on the user's senses to determine if a file is missing. That was the whole point of the missing file placeholders in the table; so it would be immediately discernible that something was missing.
